# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build-and-test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: checkout repository
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      # 3. Install dependencies using Yarn
      - name: Install Dependencies
        run: yarn install

      # 4. Build the project
      - name: Build Project
        run: yarn build

      # 5. Run Unit Tests
      - name: Run Unit Tests
        run: yarn test

      # 6. Run Integration Tests
      - name: Run Integration Tests
        run: yarn test:e2e

      # 7. Upload JUnit Test Results
      - name: Upload JUnit Test Results
        if: always() # Ensure this step runs even if previous steps fail
        uses: actions/upload-artifact@v3
        with:
          name: junit-test-results
          path: |
            **/test-results/unit/*.xml
            **/test-results/integration/*.xml
